### ISSUE TITLE
[QUESTION] form-data와 json 차이

### ISSUE THREAD

**Issue by smeil123** [roongang/WMmarket#42]
backend controller에서 차이 말고
frontend에서의 차이는 무엇인가요?

**Comment by shininghyunho** [comment]
# form-data 와 json 차이
form-data 가 뭐야
- form-data 는 입력양식을 태그로 둘러싼 형태의 요청.

왜 필요한가?
- 다른 요청들은 json으로 보낼수 있는데 이미지는 이미지 자체와 이미지 메타데이터가 필요함
- 이미지를 보낼수있는 방법을 생각해낸게 multipart 형태!
- 그래서 이미지를 보낼때 form 형식으로 전송하고 인코딩 타입을 multipart로 지정해서 사용 
- hearder에 content-type이 multipart/form-data로 지정돼야함

우리가 쓰는 이유
- 거래글(dealPost) 작성시 이미지가 option으로 들어갈수있음
- 그래서 다른 api와는 다르게 form 형식으로 데이터를 전송함!
- 다만 거래글 수정시(/api/v1/deal-posts/{dealPostId})에는 이미지를 제외하고 수정하고있어 json으로 요청함.(이미지만 수정하는 api가 따로 존재함.)
---
# front code 예시
## HTML
```
<form method="POST" enctype="multipart/form-data" id="uploadForm">
    <input type="file" name="profile" />
    <button id='btnUpload'>확인</button>
</form>
```
## Javascript
```
$('#btnUpload').on('click', function(event) {
    event.preventDefault();
    
    var form = $('#uploadForm')[0]
    var data = new FormData(form);
    
    $('#btnUpload').prop('disabled', true);
	
    $.ajax({
        type: "POST",
        enctype: 'multipart/form-data',
        url: "/upload",
        data: data,
        processData: false,
        contentType: false,
        cache: false,
        timeout: 600000,
        success: function (data) {
        	$('#btnUpload').prop('disabled', false);
        	alert('success')
        },
        error: function (e) {
            $('#btnUpload').prop('disabled', false);
            alert('fail');
        }
    });
})
```
---
# 실제 요청 예시
## form
![image](https://user-images.githubusercontent.com/46080945/148853997-c776ab1b-9fda-4ebc-80a5-58b1ac949d1a.png)
## json
![image](https://user-images.githubusercontent.com/46080945/148854317-0d8f3b59-71b3-4579-bca6-55c7e068082c.png)
