### ISSUE TITLE
[TODO] API 요청

### ISSUE THREAD

**Issue by smeil123** [roongang/WMmarket#43]
* dealPost
1. POST로 글 생성 성공시 response에 생성된 id 전달해주기
2. 전체 게시글 호출하는데 아래 조건을 인자로 넣을 수 있는 기능
    * 검색조건 : 거래가 완료된 게시글 제외&포함, 조회수가 높은 순서대로, 최근 생선된 순서대로
    * 페이지네이션이 되도록 설계
3. 내가 쓴 게시글 목록을 조회할 수 있는 기능
4. keyword로 게시글을 검색할 수 있는 기능
    * 검색 조건 : 제목에만 포함, 제목&내용에 포함

**Comment by shininghyunho** [comment]
1번 작업 https://github.com/roongang/WMmarket/pull/44#issue-1099782518

**Comment by shininghyunho** [comment]
3번 작업 https://github.com/roongang/WMmarket/blob/306cdafe75add3f53e5a0e3bff1e83076845b91e/src/main/java/com/around/wmmarket/controller/UserApiController.java#L274

**Comment by smeil123** [comment]
5. user 생성확인 wm-market.herokuapp.com/api/v1/users
    - get으로 변경하고 body값 없애기
 6. user 이미지만 업로드 추가

**Comment by shininghyunho** [comment]
2번 작업 (조회수)

**Comment by shininghyunho** [comment]
2,4번 작업
Pagination 기능 추가
(검색 포함)
Pagination 사용법에 대한 정리는 [Wiki](https://github.com/roongang/WMmarket/wiki/Pagination)에 정리해 놓았습니다.

**Comment by shininghyunho** [comment]
> 5. user 생성확인 wm-market.herokuapp.com/api/v1/users
>    
>    * get으로 변경하고 body값 없애기
> 6. user 이미지만 업로드 추가

5,6번 작업 반영되었습니다.
